-- 연도별 가장 큰 대장균의 크기
# SELECT YEAR(DIFFERENTIATION_DATE), MAX(SIZE_OF_COLONY) as 'MAX_SIZE_OF_COLONY'
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE)

SELECT 
    YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
    MAX_SIZE_OF_COLONY - SIZE_OF_COLONY AS 'YEAR_DEV',
    ID
FROM ECOLI_DATA e1
    LEFT JOIN (
        -- 연도별 가장 큰 대장균의 크기 (서브쿼리)
        SELECT YEAR(e.DIFFERENTIATION_DATE) as 'YEAR', MAX(e.SIZE_OF_COLONY) as 'MAX_SIZE_OF_COLONY'
        FROM ECOLI_DATA e
        GROUP BY YEAR(e.DIFFERENTIATION_DATE)
    ) e2
    ON YEAR(e1.DIFFERENTIATION_DATE) = e2.YEAR
ORDER BY YEAR asc, YEAR_DEV asc
